services:
  - type: web
    name: civegpt-backend
    env: python
    region: oregon
    plan: free
    pythonVersion: "3.11.0"
    buildCommand: |
      pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"