services:
  - type: web
    name: civegpt-backend
    env: python
    region: oregon
    plan: free
    build: pip install -r backend/requirements.txt
    start: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
